### ISSUE TITLE
S3 Producer doesn't support AWS role switching

### ISSUE THREAD

**Issue by ppar** [trivago/gollum#103]
When using AWS STS credentials, `producer/s3.go` does not know how to switch to the required AWS STS role. 

Given a Gollum configuration:

```
"StdIn":
    Type: "consumer.Console"
    Streams: "console"
    Fuse: "file"

"S3Out":
    Type: "producer.S3"
    Region: "eu-central-1"
    CredentialType: "shared"
    CredentialFile: "/home/myusername/.aws/credentials"
    CredentialProfile: "test_profile"
    StreamMapping:
        "console": "my-testbucket/console"
        "*" : "my-testbucket/asterisk"
```

And an `~/.aws/credentials` file:

```
[test_profile]
aws_access_key_id = AKI.....
aws_secret_access_key = asdfgh1234
source_profile = default
role_arn = arn:aws:iam::123456789:role/foo-bar
region = eu-central-1
output = table
```

Gollum will simply try to connect using the default profile of that user and ignores the `role_arn` setting. 

There seems to be support for assuming roles in the AWS Go SDK:

https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/stscreds/assume_role_provider.go

So it could be useful to add support for this in Gollum.
