### ISSUE TITLE
Gollum shuts down uncleanly

### ISSUE THREAD

**Issue by ppar** [trivago/gollum#146]
At current master (463ce5720a459f885cd5885cbfb2674377d60371), Gollum outputs the following stack trace when shutting down:

```
Panic shutdown: runtime error: invalid memory address or nil pointer dereference
	/Users/pparkkali/src/go/src/github.com/trivago/gollum/vendor/github.com/trivago/tgo/runtime.go:61
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:514
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/runtime/panic.go:489
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/runtime/panic.go:63
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/runtime/signal_unix.go:290
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/time/sleep.go:75
	/Users/pparkkali/src/go/src/github.com/trivago/gollum/core/logconsumer.go:124
	/Users/pparkkali/src/go/src/github.com/trivago/gollum/coordinator.go:139
	/Users/pparkkali/src/go/src/github.com/trivago/gollum/vendor/github.com/trivago/tgo/runtime.go:97
	/usr/local/opt/home-brew/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197
```

The same stack trace is generated when killing Gollum using Ctrl-C and at the end of a  `consumer.Profiler` run with `KeepRunning` set to `false`.

Example config:

```yaml
# -*- yaml -*-

JunkGenerator:
  Type: "consumer.Profiler"
  Message: "%20s"
  Streams: "junkstream_00"
  KeepRunning: false
  Runs: 5
  Batches: 3
  DelayMs: 100

JunkPrinter:
  Type: "producer.Console"
  Streams: "junkstream_00"
  Modulators:
    - "format.Envelope":
        Prefix: "[JUNK] "

# Print Gollum's application log to stdout/stderr
GollumLogPrinter:
    Type: "producer.Console"
    Console: "stdout"
    #Console: "stderr"
    Streams: "_GOLLUM_"
    Enable: true
    Modulators:
        # Prepend a timestamp
        - "format.Timestamp"
        # Prepend "[_GOLLUM_] " and append a newline
        - "format.Envelope":
            Prefix: "[_GOLLUM_] "
```
