### ISSUE TITLE
Streaming _GOLLUM_ through router.Distribute with 1> TargetStreams blocks indefinitely

### ISSUE THREAD

**Issue by ppar** [trivago/gollum#148]
When attaching a `router.Distribute` with > 1 `TargetStream` to the internal `_GOLLUM_` stream, the process blocks indefinitely and no messages are produced.

Working configuration, prints `_GOLLUM_` messages to stdout:

```
GollumLogDist:
  Type: "router.Distribute"
  Stream: "_GOLLUM_"
  TargetStreams:
    - "gollum_log_00"
    #- "gollum_log_01"

GollumLogPrinterStdout:
    Type: "producer.Console"
    Console: "stdout"
    Streams: "gollum_log_00"
    Enable: true
    Modulators:
        - "format.Timestamp"
        - "format.Envelope":
            Prefix: "[_GOLLUM_00_] "
```

Failing configuration, blocks indefinitely instead of printing messages:

```
GollumLogDist:
  Type: "router.Distribute"
  Stream: "_GOLLUM_"
  TargetStreams:
    - "gollum_log_00"
    - "gollum_log_01"

GollumLogPrinterStdout:
    Type: "producer.Console"
    Console: "stdout"
    Streams: "gollum_log_00"
    Enable: true
    Modulators:
        - "format.Timestamp"
        - "format.Envelope":
            Prefix: "[_GOLLUM_00_] "

GollumLogFiler:
    Type: "producer.File"
    File: "/tmp/gollum.log"
    Streams: "gollum_log_01"
    Modulators:
        - "format.Timestamp"
        - "format.Envelope":
            Prefix: "[_GOLLUM_02_] "
```
