### ISSUE TITLE
Panic when trying to use file consumer without stream configuration

### ISSUE THREAD

**Issue by mre** [trivago/gollum#151]
Gollum version: [Latest master](https://github.com/trivago/gollum/commit/463ce5720a459f885cd5885cbfb2674377d60371), compiled with `make`
Operating system: Mac OS Sierra 10.12.5

**Contents of file: gollum.conf:**
```yaml
input:
    Type: consumer.File
    File: foo
    DefaultOffset: "Oldest"

output:
   Type: producer.Console
   Streams:
    - test
```

**Contents of file: foo:**
```foo```

**Command:**
```./gollum -c gollum.conf```

**Expected behavior:**
Show error message. Something like:
"Missing 'Streams' parameter in plugin `input`. At least one stream must be defined for every plugin."

**Actual behavior:**
Runtime panic.
```
Panic shutdown: runtime error: index out of range
	.../go/src/github.com/trivago/gollum/vendor/github.com/trivago/tgo/runtime.go:61
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:514
	/usr/local/opt/go/libexec/src/runtime/panic.go:489
	/usr/local/opt/go/libexec/src/runtime/panic.go:28
	.../go/src/github.com/trivago/gollum/core/simpleconsumer.go:216
	.../go/src/github.com/trivago/gollum/core/simpleconsumer.go:182
	.../go/src/github.com/trivago/gollum/consumer/file.go:121
	.../go/src/github.com/trivago/gollum/consumer/file.go:188
	.../go/src/github.com/trivago/gollum/vendor/github.com/trivago/tgo/tio/bufferedreader.go:267
	.../go/src/github.com/trivago/gollum/consumer/file.go:231
```

**Fix:**
Define at least one stream.
```
input:
    Type: consumer.File
    File: foo
    DefaultOffset: "Oldest"
    Streams:
      - test

output:
   Type: producer.Console
   Streams:
    - test
```
Have not tested, but maybe the same bug occurs in other plugins.
