### ISSUE TITLE
Gollum with Kafka and Fallback Producer crashes at startup if Kafka Broker is unreachable

### ISSUE THREAD

**Issue by dkleuser** [trivago/gollum#213]
## Issue description
When Gollum starts with a Kafka Producer and Kafka is not reachable (yet), Gollum crashes although a Fallback Producer is configured (s. full trace in the "Steps to Reproduce" section).

Actually, the Fallback Producer should prevent Gollum from crashing if this happens or better to say: Gollum should throw an error but not crash at all.
From its output it also seems that Gollum wasn't able to recognize the configured Fallback Producer.

## Context
The behaviour could be mitigated by creating a Systemd unit file with automatic restart on failure and an increased waiting time between automatic restarts (default is 100ms, set this to 15s to make sure that Kafka is really up and running).
There was already a dependency in the unit file for Gollum to start after the Kafka unit has been started but this wasn't sufficient.

## Steps to Reproduce (for bugs)

1. Configure Gollum to start at system startup, configure Kafka to start at system startup, Gollum is set to start after Kafka, because it needs it as a target.
2. Start the system, check `journalctl -u name-of-your-gollum-unit`
3. See trace like: [gollum_trace.log](https://github.com/trivago/gollum/files/1575426/gollum_trace.log)
4. See detailed Gollum config at the bottom of this page.

### Used versions

* gollum version: v0.5.0-rc3.1
* go version: 1.9.2
* Operating System and version: Debian 9
* Kafka version: 1.0.0

### Config:

```yaml
SystemSyslogIn:
  Type: consumer.Syslogd
  Address: "udp://0.0.0.0:514"
  Format: "RFC3164"
  SetMetadata: true
  Streams: "system-syslog"
#
FallbackSpoolSystem:
  Type: producer.Spooling
  Streams: "fallback-system"
  Path: /var/run/gollum/spooling
#
GollumFileOut:
  Type: producer.File
  Streams: "_GOLLUM_"
  File: /var/log/gollum/gollum.log
  Modulators:
    - format.Envelope
  Rotation:
    Enable: true
    Rotation: true
    At: "23:59"
#
SystemKafkaOut:
  Type: producer.Kafka
  Streams: ["system-syslog", "_GOLLUM_"]
  Modulators:
    -
      format.Clear:
        ApplyTo: "hostname"
    -
      format.Hostname:
        Separator: ""
        ApplyTo: "hostname"
  FallbackStream: "fallback-system"
  Topics:
    "system-syslog" : "system-logs-search-raw"
    "_GOLLUM_" : "system-logs-search-raw"
  Compression: "lz4"
  Servers: ['server0:9092', 'server1:9092']
  KeyFrom: "hostname"
#
KafkaSyslogIn:
  Type: consumer.Syslogd
  Address: "udp://0.0.0.0:515"
  Format: "RFC3164"
  SetMetadata: true
  Streams: "kafka-syslog"
#
FallbackSpoolSystemKafka:
  Type: producer.Spooling
  Streams: "fallback-kafka"
  Path: /var/run/gollum/spooling
#
KafkaKafkaOut:
  Type: producer.Kafka
  Streams: ["kafka-syslog"]
  FallbackStream: "fallback-kafka"
  Topics:
    "kafka-syslog" : "system-logs-kafka-raw"
  Compression: "lz4"
  Servers: ['server0:9092', 'server1:9092']
  KeyFrom: "hostname"
```
