### ISSUE TITLE
format.MetadataCopy: unexpected change in metadata if msg.data.payload get modified

### ISSUE THREAD

**Issue by mahdi-hdi** [trivago/gollum#229]
## Issue description

By using `format.MetadataCopy` the value of payload is copied to `metadata['your_key']`. After that any changes to the payload would be appeared in `metadata['your_key']` as well. 

## Steps to Reproduce (for bugs)

1. Run gollum with the following configuration.
2. Enter `aaaa:bb`
3. Expect out must be `key#payload` which is `aaaa:bb#bb`
4. However the output is `bbaa:bb#bb` 

### Used versions
* gollum version: `v0.5.3`
* go version: `go1.10.3 linux/amd64`

### Config:

```yaml
default-input:
    Type: producer.Console
    Streams:
        - console

default-output:
    Type: consumer.Console
    Streams:
        - console
    Modulators:
        ## Suppose that payload is 'aaaa:bb'
        ## Copy payload to metadata['key']
        ## So metadata['key'] is now 'aaaa:bb'  and payload is 'aaaa:bb' as well
        - format.MetadataCopy:
            ApplyTo: key

       ## Split the payload and pick index 1
       ## So metadata['key'] is now 'aaaa:bb' and payload is 'bb'
        - format.SplitPick:
            Index: 1
            Delimiter: ':'

       ## In order to print value of metadata prepend it to message payload
       ## So metadata['key'] must be 'aaaa:bb' and payload be 'key#payload' 
       ## which is 'aaaa:bb#bb'
        - format.MetadataCopy:
            Key: key
            Separator: '#'
            Mode: prepend
       
       ## BUT the final payload is 'bbaa:bb#bb'
        - format.Envelope:
            Postfix: "\n"
```

## Context and Possible Solution

```golang
package main

import "fmt"

func main() {
	payload := []byte("aaaabb")
	metadata := map[string][]byte{}
	
	//
	// format.MetadataCopy:
	//     ApplyTo: key
	//
	metadata["key"] = payload
	
	///////////////////////////////////////////////////
	// A suggested approach could be:                //
	//                                               //
	// metadata["key"] = make([]byte, len(payload))  //
	// copy(metadata["key"], payload)                //
	//                                               //
	// instead of:                                   //
	//                                               //
	// metadata["key"] = payload                     //
	//                                               //
	///////////////////////////////////////////////////
	
	
	fmt.Printf("payload: %s\n", payload)
	fmt.Printf("metadata: %s\n", metadata)
	
	//
	// Modifiying payload with other formaters
	//     
	payload = payload[:2]
	copy(payload, []byte("xx"))
	
	fmt.Printf("payload: %s\n", payload)
	fmt.Printf("metadata: %s\n", metadata)

}
```

Accordingly, a possible solution could be here [metadata.go:22](https://github.com/trivago/gollum/blob/3d7deb20ed8e122987c422b03e6c7aac62fa8145/core/metadata.go#L22):

```golang
# Change from:
meta[key] = value

# To:
meta[key] = make([]byte, len(value))
copy(meta[key], value)
```
