### ISSUE TITLE
is documentation outdated?

### ISSUE THREAD

**Issue by serii833** [trivago/gollum#240]
is [documentation](https://gollum.readthedocs.io/en/latest/) outdated? 
I'm trying "Hello World" examples and they don't seem to be correct. 
I was able to run them with config tweaking. 
I've found some other inconsistencies through docs.
Am I missing something?

**Comment by andygrunwald** [comment]
Hey @serii833,
can you provide us a little bit more information?
E.g.,
* Can you post the config you used?
* Can you post the config you tweaked and post the working config?
* Which Gollum version are you using?

**Comment by serii833** [comment]
my Gollum version 0.5.3 (precompiled binary)

I take first example from this page https://gollum.readthedocs.io/en/latest/src/examples/helloWorld.html
```yaml
- "consumer.Console":
    Stream: "console"

- "producer.Console":
    Formatter: "format.Envelope"
    Stream:
        - "*"
        - "_GOLLUM_"
```
when i try to run Gollum with this config I've got following:
```bash
[2018-12-18 22:44:14 +03] ERROR Failed to read config error=yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]tcontainer.MarshalMap
```


after making config to look like this 
```yaml
"consumer.Console":
  Type: consumer.Console
  Streams: 
    - "console"

"producer.Console":
  Type: producer.Console
  # Formatter: "format.Envelope"
  # ERROR Failed to instantiate producer 'producer.Console' error=Unknown configuration key 'Formatter' in 'producer.Console'
  Streams:
    - "*"
    - "_GOLLUM_"
```
Gollum starts and working


Another example
this page https://gollum.readthedocs.io/en/latest/src/gen/consumer/console.html describes "console" consumer. 
There is parameter "Modulators" among others. 
```
Defines a list of modulators to be applied to a message
```
there is no "modulators" section in docs, but there is a "filters" section.
I suggested that modulator are filters and it made sense.

**Comment by M3t0r** [comment]
Yeah, it seems that the examples are still using the old v0.4 keywords although the general structure has been updated. The transformation is mentioned in the [release notes](https://gollum.readthedocs.io/en/latest/src/releaseNotes/v0.5.0.html#formatters-and-filters-are-now-modulators).

`format.Envelope` is a modulator that you can specify in the `modulators` list of consumers and producers. Check [the example for `format.Envelope`](https://gollum.readthedocs.io/en/latest/src/gen/formatter/envelope.html#examples).

Your config should then look like this:
```yaml
"consumer.Console":
  Type: consumer.Console
  Streams: 
    - "console"

"producer.Console":
  Type: producer.Console
  Modulators:
    - format.Envelope
  Streams:
    - "*"
    - "_GOLLUM_"
```
