### ISSUE TITLE
Allow direct access to _DROPPED_ without having to use the LoopBack consumer.

### ISSUE THREAD

**Issue by MaxBosse** [trivago/gollum#4]
Currently, as of version 0.3.2, you have to define the [Loopback consumer](http://gollum.readthedocs.org/en/latest/consumers/loopback.html) if you want to use the \_DROPPED\_ stream mentioned in the ChannelTimeoutMs parameter of the [Kafka producer](http://gollum.readthedocs.org/en/latest/producers/kafka.html#parameters).

Because there is no case in which you would not want to use the \_DROPPED\_ stream with a ChannelTimeoutMs set higher than 0, it would make sense to have the loopback-consumer functionality for the \_DROPPED\_ stream from the get-go.

Example config which doesn't work right but would with the proposed change:
```yaml
- "consumer.Console":
    Enable: true
    Stream: "textStream"

- "producer.Kafka":
    Enable: true
    Channel: 65535
    ChannelTimeoutMs: 10
    Stream:
      - "textStream"
    Topic:
      "textStream": "webserver_textStream"
    Servers:
      - "192.168.0.5:9092"
      - "192.168.0.6:9092"
      - "192.168.0.7:9092"
    Formatter: "format.Timestamp"
    Timestamp: "20060102150405 "

- "producer.File":
    File: "/appdata/gollum/dropped/textStream.log"
    Stream:
      - "_DROPPED_"
    Formatter: "format.Envelope"
    Rotate: true
    RotateSizeMB: 512
    RotateAt: "00:00"
    Compress: true
```

Example which does work using the LoopBack consumer:
```yaml
- "consumer.Console":
    Enable: true
    Stream: "textStream"

- "consumer.LoopBack":
    Enable: true
    Channel: 8192
    Routes:
      "_DROPPED_": "dropped"

- "producer.Kafka":
    Enable: true
    Channel: 65535
    ChannelTimeoutMs: 10
    Stream:
      - "textStream"
    Topic:
      "textStream": "webserver_textStream"
    Servers:
      - "192.168.0.5:9092"
      - "192.168.0.6:9092"
      - "192.168.0.7:9092"
    Formatter: "format.Timestamp"
    Timestamp: "20060102150405 "

- "producer.File":
    File: "/appdata/gollum/dropped/textStream.log"
    Stream:
      - "dropped"
    Formatter: "format.Envelope"
    Rotate: true
    RotateSizeMB: 512
    RotateAt: "00:00"
    Compress: true
```
