### ISSUE TITLE
Improve 0.5.0 config layout

### ISSUE THREAD

**Issue by arnecls** [trivago/gollum#85]
After an internal discussion we came to the point that the current Gollum 0.5.0 format can be improved further in terms of maintainability and reusability.
As we're pushing a config change with 0.5.0 anyway it does make sense to add this on top of the current changes even though they have not been released yet.

Proposed example:

```yaml
WriteToKafka:
  Type: Producer
  Stream: "*"
  Modulators:
    - filter.Rate
    - format.Hostname
    - format.Envelope
      PostFix: "\r\n"
  Plugins:
    - producer.Kafka:
      Broker: ["192.168.0.1","192.168.0.3","192.168.0.2"]
      Topic: "*"
    - producer.Elasticsearch:
      Master: "192.168.10.1"
      Index: "*"
```

To achieve this we have to adjust the base types and separate the actually plugin configuration from the "standard framework" configuration.
Creating multiple plugins out of a single config block can be done by generating multiple config blocks from one block in the config parsing section. As an example: the config above would be separated into two blocks with a producer.Kafka as single item and a producer.Elasticsearch as single item.

**Comment by arnecls** [comment]
If the preprocessing generates the following configs out of the example above, we don't need to change anything in the handling of the configuration:

```yaml
WriteToKafka0:
  Type: producer.Kafka
  Stream: "*"
  Modulators:
    - filter.Rate
    - format.Hostname
    - format.Envelope
      PostFix: "\r\n"
  Broker: ["192.168.0.1","192.168.0.3","192.168.0.2"]
  Topic: "*"

WriteToKafka1:
  Type: producer.ElasticSearch
  Stream: "*"
  Modulators:
    - filter.Rate
    - format.Hostname
    - format.Envelope
      PostFix: "\r\n"
  Master: "192.168.10.1"
  Index: "*"
```

**Comment by msiebeneicher** [comment]
The feature is ready to merge. Here the example config in the final state:

```yml
WriteToKafka:
  Type: aggregate
  Stream: "*"
  Modulators:
    - filter.Rate
    - format.Hostname
    - format.Envelope
      PostFix: "\r\n"
  Aggregate:
    kafka:
      Type: producer.Kafka
      Broker: ["192.168.0.1","192.168.0.3","192.168.0.2"]
      Topic: "*"
    elasticsearch:
      Type: producer.Elasticsearch
      Master: "192.168.10.1"
      Index: "*"
```
